---
- hosts: all
  become: true
  tasks:

  - name: install python3-pip package
    apt:
      name:
        - python3
        - python3-pip
      state: present

    - name: use pip3 as the default pip
      command: update-alternative --install /usr/bin/pip pip /usr/bin/pip3 1

    - name: use python3 as the default python
      command: update-alternative --install /usr/bin/python python /usr/bin/python3 1
